### ISSUE TITLE
Windows line endings cause `mwb init` failure on OS X

### ISSUE THREAD

**Issue by trxcllnt** [aunz/mwb#2]
Attempting to execute `npm run mwb init` errors with `env: node\r: No such file or directory`. Seems like node on OS X [can't run](http://stackoverflow.com/a/31041038/3117331) files with Windows line endings. 

Changing the line-endings of `ndoe_modules/mwb/bin/mwb.js` to Unix in Sublime Text fixed the issue.

**Comment by aunz** [comment]
Thanks for pointing this out, I will fix this.

**Comment by trxcllnt** [comment]
@aunz thanks for the project, it's helping me out a lot!
